import { Prisma } from '~/prisma';

export type Args =
   | Prisma.CommentAggregateArgs
   | Prisma.CommentCountArgs
   | Prisma.CommentCreateArgs
   | Prisma.CommentCreateManyArgs
   | Prisma.CommentDeleteArgs
   | Prisma.CommentFindFirstArgs
   | Prisma.CommentFindManyArgs
   | Prisma.CommentFindUniqueArgs
   | Prisma.CommentGroupByArgs
   | Prisma.CommentUpdateArgs
   | Prisma.CustomerAggregateArgs
   | Prisma.CustomerCountArgs
   | Prisma.CustomerCreateArgs
   | Prisma.CustomerCreateManyArgs
   | Prisma.CustomerDeleteArgs
   | Prisma.CustomerFindFirstArgs
   | Prisma.CustomerFindManyArgs
   | Prisma.CustomerFindUniqueArgs
   | Prisma.CustomerGroupByArgs
   | Prisma.CustomerUpdateArgs
   | Prisma.DiscountAggregateArgs
   | Prisma.DiscountCountArgs
   | Prisma.DiscountCreateArgs
   | Prisma.DiscountCreateManyArgs
   | Prisma.DiscountDeleteArgs
   | Prisma.DiscountFindFirstArgs
   | Prisma.DiscountFindManyArgs
   | Prisma.DiscountFindUniqueArgs
   | Prisma.DiscountGroupByArgs
   | Prisma.DiscountUpdateArgs
   | Prisma.ImageAggregateArgs
   | Prisma.ImageCountArgs
   | Prisma.ImageCreateArgs
   | Prisma.ImageCreateManyArgs
   | Prisma.ImageDeleteArgs
   | Prisma.ImageFindFirstArgs
   | Prisma.ImageFindManyArgs
   | Prisma.ImageFindUniqueArgs
   | Prisma.ImageGroupByArgs
   | Prisma.ImageUpdateArgs
   | Prisma.LaptopAggregateArgs
   | Prisma.LaptopCountArgs
   | Prisma.LaptopCreateArgs
   | Prisma.LaptopCreateManyArgs
   | Prisma.LaptopDeleteArgs
   | Prisma.LaptopFindFirstArgs
   | Prisma.LaptopFindManyArgs
   | Prisma.LaptopFindUniqueArgs
   | Prisma.LaptopGroupByArgs
   | Prisma.LaptopUpdateArgs
   | Prisma.PassageAggregateArgs
   | Prisma.PassageCountArgs
   | Prisma.PassageCreateArgs
   | Prisma.PassageCreateManyArgs
   | Prisma.PassageDeleteArgs
   | Prisma.PassageFindFirstArgs
   | Prisma.PassageFindManyArgs
   | Prisma.PassageFindUniqueArgs
   | Prisma.PassageGroupByArgs
   | Prisma.PassageUpdateArgs
   | Prisma.PersonAggregateArgs
   | Prisma.PersonCountArgs
   | Prisma.PersonCreateArgs
   | Prisma.PersonCreateManyArgs
   | Prisma.PersonDeleteArgs
   | Prisma.PersonFindFirstArgs
   | Prisma.PersonFindManyArgs
   | Prisma.PersonFindUniqueArgs
   | Prisma.PersonGroupByArgs
   | Prisma.PersonUpdateArgs
   | Prisma.PostAggregateArgs
   | Prisma.PostCountArgs
   | Prisma.PostCreateArgs
   | Prisma.PostCreateManyArgs
   | Prisma.PostDeleteArgs
   | Prisma.PostFindFirstArgs
   | Prisma.PostFindManyArgs
   | Prisma.PostFindUniqueArgs
   | Prisma.PostGroupByArgs
   | Prisma.PostUpdateArgs
   | Prisma.PriceMapAggregateArgs
   | Prisma.PriceMapCountArgs
   | Prisma.PriceMapCreateArgs
   | Prisma.PriceMapCreateManyArgs
   | Prisma.PriceMapDeleteArgs
   | Prisma.PriceMapFindFirstArgs
   | Prisma.PriceMapFindManyArgs
   | Prisma.PriceMapFindUniqueArgs
   | Prisma.PriceMapGroupByArgs
   | Prisma.PriceMapUpdateArgs
   | Prisma.PurchaseAggregateArgs
   | Prisma.PurchaseCountArgs
   | Prisma.PurchaseCreateArgs
   | Prisma.PurchaseCreateManyArgs
   | Prisma.PurchaseDeleteArgs
   | Prisma.PurchaseFindFirstArgs
   | Prisma.PurchaseFindManyArgs
   | Prisma.PurchaseFindUniqueArgs
   | Prisma.PurchaseGroupByArgs
   | Prisma.PurchaseUpdateArgs
   | Prisma.UserAggregateArgs
   | Prisma.UserCountArgs
   | Prisma.UserCreateArgs
   | Prisma.UserCreateManyArgs
   | Prisma.UserDeleteArgs
   | Prisma.UserFindFirstArgs
   | Prisma.UserFindManyArgs
   | Prisma.UserFindUniqueArgs
   | Prisma.UserGroupByArgs
   | Prisma.UserUpdateArgs
   | Prisma.VideoAggregateArgs
   | Prisma.VideoCountArgs
   | Prisma.VideoCreateArgs
   | Prisma.VideoCreateManyArgs
   | Prisma.VideoDeleteArgs
   | Prisma.VideoFindFirstArgs
   | Prisma.VideoFindManyArgs
   | Prisma.VideoFindUniqueArgs
   | Prisma.VideoGroupByArgs
   | Prisma.VideoUpdateArgs