export type ObjectType = 
                        | 'Comment' 
                        | 'Customer' 
                        | 'Discount' 
                        | 'Image'
                        | 'Laptop'
                        | 'Passage'
                        | 'Person'
                        | 'Post'
                        | 'PriceMap'
                        | 'Purchase'
                        | 'User'
                        | 'Video'